openapi: 3.0.0
info:
  description: |
    This is the RESTful API for a user to update their password in WSO2 Identity Server.
  version: "v1"
  title: "WSO2 Identity Server - Password API Definition"
  contact:
    name: "WSO2 Identity Server"
    url: "https://wso2.com/identity-and-access-management/"
    email: "architecture@wso2.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

servers:
  - url: 'https://localhost:9443/t/{tenant-domain}/api/users/v1'
    variables:
      tenant-domain:
        default: carbon.super
        description: Tenant domain in which the API is invoked

security:
  - OAuth2: []
  - BasicAuth: []

tags:
  - name: me
    description: Operations for the authenticated user.


paths:
  /me/password:
    put:
      tags:
        - me
      summary: Update user password
      description: |
        This API is used to update the password of the authenticated user.

        <b>Permission required:</b>
            * none
        <b>Scope required:</b>
            * internal_login
      operationId: updatePassword
      requestBody:
        description: Password update request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordUpdateRequest'
      responses:
        '200':
          description: Password successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PasswordUpdateResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/ServerError'
      x-wso2-request: |
        curl -X PUT "https://localhost:9443/api/users/v1/me/password" -H "Authorization: Bearer <access_token>" -H "Content-Type: application/json" -d '{"currentPassword": "CurrentPassword123", "newPassword": "NewPassword123"}'
      x-wso2-response: |
        HTTP/1.1 200 OK
        {
          "status": "SUCCESS",
          "message": "Password updated successfully"
        }

components:
  schemas:
    #-----------------------------------------------------
    # Password Update Request object
    #-----------------------------------------------------
    PasswordUpdateRequest:
      type: object
      required:
        - currentPassword
        - newPassword
      properties:
        currentPassword:
          type: string
          description: Current password of the user
          example: "CurrentPassword123"
        newPassword:
          type: string
          description: New password for the user
          example: "NewPassword123"

    #-----------------------------------------------------
    # Password Update Response object
    #-----------------------------------------------------
    PasswordUpdateResponse:
      type: object
      properties:
        status:
          type: string
          description: Status of the password update operation
          example: "SUCCESS"
        message:
          type: string
          description: Message describing the result of the operation
          example: "Password updated successfully"

    #-----------------------------------------------------
    # Error object
    #-----------------------------------------------------
    ErrorDTO:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          example: "60001"
        message:
          type: string
          example: "Invalid current password"
        description:
          type: string
          example: "The current password you entered is incorrect."
        traceId:
          type: string
          example: "e0fbcfeb-3617-43c4-8dd0-7b7d38e13047"

  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://localhost:9443/oauth2/authorize'
          tokenUrl: 'https://localhost:9443/oauth2/token'
          scopes: {}

  #-----------------------------------------------------
  # Descriptions of common responses
  #-----------------------------------------------------
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDTO'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDTO'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDTO'
    ServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDTO'

