openapi: 3.0.0
info:
  title: "WSO2 Identity Server - User Password Management API"
  description: |
    This is the RESTful API for a user to change their password in WSO2 Identity Server.
  contact:
    name: "WSO2 Identity Server"
    url: "https://wso2.com/identity-and-access-management/"
    email: "architecture@wso2.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  version: "v1"

servers:
  - url: 'https://localhost:9443/t/{tenant-domain}/api/users/v1'
    variables:
      tenant-domain:
        default: carbon.super
        description: Tenant domain in which the API is invoked

security:
  - OAuth2: []

tags:
  - name: me
    description: Operations for the authenticated user.

paths:
  /me/change-password:
    post:
      tags:
        - me
      summary: Change user password
      description: |
        This API is used to change the password of the authenticated user.

        <b>Permission required:</b>
            * none
        <b>Scope required:</b>
            * internal_login
      operationId: changePassword
      requestBody:
        description: Password change request.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordChangeRequest'
      responses:
        '204':
          $ref: '#/components/responses/Success'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/ServerError'

components:
  schemas:
    #-----------------------------------------------------
    # Password Change Request object
    #-----------------------------------------------------
    PasswordChangeRequest:
      type: object
      required:
        - currentPassword
        - newPassword
      properties:
        currentPassword:
          type: string
          description: Current password of the user.
          example: "CurrentPassword123"
        newPassword:
          type: string
          description: New password to set for the user.
          example: "NewPassword456"

    #-----------------------------------------------------
    # Error object
    #-----------------------------------------------------
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          example: "PWD-10001"
        message:
          type: string
          example: "Invalid current password"
        description:
          type: string
          example: "The current password provided is incorrect."
        traceId:
          type: string
          example: "e0fbcfeb-3617-43c4-8dd0-7b7d38e13047"

  #-----------------------------------------------------
  # Descriptions of common responses
  #-----------------------------------------------------
  responses:
    Success:
      description: Password successfully changed
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            InvalidCurrentPassword:
              $ref: '#/components/examples/InvalidCurrentPassword'
            PasswordPolicyViolation:
              $ref: '#/components/examples/PasswordPolicyViolation'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  #-----------------------------------------------------
  # Examples
  #-----------------------------------------------------
  examples:
    InvalidCurrentPassword:
      summary: Wrong current password
      value:
        code: "PWD-10001"
        message: "Invalid current password"
        description: "The current password provided is incorrect."
        traceId: "e0fbcfeb-3617-43c4-8dd0-7b7d38e13047"
    PasswordPolicyViolation:
      summary: New password too weak
      value:
        code: "PWD-10003"
        message: "Password policy violation"
        description: "The minimum length of password should be 8."
        traceId: "e0fbcfeb-3617-43c4-8dd0-7b7d38e13047"

  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://localhost:9443/oauth2/authorize'
          tokenUrl: 'https://localhost:9443/oauth2/token'
          scopes:
            internal_login: Internal login scope required for password change
